api_platform:
    title: "REST API Symfony to manage Car ----- Zanak'i Aba ------"
    description: "Created by 'back => Angelo Hackeretovic' and 'front => Kererion'"
    version: '1.0.0'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    # formats:
    #     json: ['application/json']
    #     jsonld: ['application/ld+json']
    #     html: ['text/html']
    #     multipart: ['multipart/form-data']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header