vich_uploader:
    db_driver: orm

    mappings:
        media_object:
            uri_prefix: /media
            upload_destination: '%kernel.project_dir%/public/images/media'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        cars_image:
            uri_prefix: /images/cars
            upload_destination: '%kernel.project_dir%/public/images/cars'
            namer: Vich\UploaderBundle\Naming\OrignameNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
